---
title: "Vectors in R and Regular Expressions"
author: "Suraj Bhattarai"
date: "September 19, 2018"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Alzebric Expressions
```{r}
x <- 1.1
a <- 2.2
b <- 3.3

z <- x^a^b
print(z)

z <- x^a*b
print(z)

z <- 3*x^3 + 2*x^2 + 1
print(z)
```

## 2. Creating vectors
```{r}
seq8 <- seq(from=1, to=8, by=1) # gives sequence from 1 to 8
seq7 <- seq(from=7, to=1, by=-1) # gives sequence from 7 to 1

VectorA <- c(seq8,seq7) # c combines two vectors 
print(VectorA)

seq5 <- seq(from=1, to=5, by=1)
VectorB <- rep(x=seq5, times=seq5) # repeating times=seq5 will repeat every element in the vector seq5 by it's own value. so 1 will be repeated one time, 2 will be twice, 3 will be thrice etc.
print(VectorB)

seq5inv <- seq(from=5, to=1, by=-1) # creates a vector 5 to 1
VectorC <- rep(x=seq5inv, c(seq(1,5))) # repeates vector by sequence 1 to 5, meaning first element in the vector 5 will be repeated once, 4 will be reepated twice and so on. 
print(VectorC)
```

## 3. Random numbers and polar coordinates

```{r}
Rnum <- runif(2) # creating two random numbers, by default it gives numbers between 0 and 1. 
x <- Rnum[1] # assigning first random number as x
y <- Rnum[2] # assigning second random number as y
PCr <- sqrt(x^2+y^2) # polar coordinate r 
ACTheta <- atan(y/x) # angular coordinate theta
print(PCr)
print(ACTheta)
```

## 4. Manipulating a vector
```{r}
queue <- c("sheep", "fox", "owl", "ant") # initial queue of animals to enter into the boat
print(queue) 
queueSer <- c(queue, "serpent") # queue after serpent arrives 
print(queueSer)
queueShe <- queueSer[-1] # queue after sheep moves in the boat, -[1] says to remove first element from the vector
queueDon <- c("Donkey", queueShe) # as Donkey comes to the front of the line
print(queueDon)

queueSer <- queueDon[-5] # serpent leaves 
print(queueSer)

queueOwl <- queueSer[-3] # owl leaves too
print(queueOwl)

queueAph <- append(x=queueOwl, values = "Aphid", after = 2) # append function adds an element, after 2 means to add after second element 
print(queueAph)
which(queueAph == "Aphid") # it gives the position of Aphid in the vector
```

## 5. Creating a vector
```{R}
A <- seq(from=1, to=100, by=1)
B <- A [!(!A%%2) + (!A%%3) + (!A%%7)]
print(B)
```
## 6. Regular expression for text editing

```
First String	Second	1.22,3.4
Second	More Text	1.555555	2.2220
Third	x	3	124
```
```
Find \t
replace ,
```

```
First String,Second,1.22,3.4
Second,More Text,1.555555,2.2220
Third,x,3,124
```

## 7. Regular expression for text editing

```
Ballif, Bryan, University of Vermont
Ellison, Aaron, Harvard Forest
Record, Sydne, Bryn Mawr
```
```
Find (\w+), (\w+), (\w+.*)
Replace \2 \1 [(\3)]
```
```
Bryan Ballif [University of Vermont]
Aaron Ellison [Harvard Forest]
Sydne Record [Bryn Mawr]

```
## 8. Regular expression for text editing

```
0001 Georgia Horseshoe.mp3 0002 Billy In The Lowground.mp3 0003 Cherokee Shuffle.mp3 0004 Walking Cane.mp3
```
```
Find .mp3
Replace .mp3\n

```
```
0001 Georgia Horseshoe.mp3
 0002 Billy In The Lowground.mp3
 0003 Cherokee Shuffle.mp3
 0004 Walking Cane.mp3

```
```
find  0
replace 0

```
```
0001 Georgia Horseshoe.mp3
0002 Billy In The Lowground.mp3
0003 Cherokee Shuffle.mp3
0004 Walking Cane.mp3
```
```
Find (\d{4}) (.*).mp3
Replace \2_\1.mp3

```
```
Georgia Horseshoe_0001.mp3
Billy In The Lowground_0002.mp3
Cherokee Shuffle_0003.mp3
Walking Cane_0004.mp3
```

## 9. Regular expression for text editing

```
Camponotus,pennsylvanicus,10.2,44
Camponotus,herculeanus,10.5,3
Myrmica,punctiventris,12.2,4
Lasius,neoniger,3.3,55
```
```
find (\w)\w+,(\w+),\d+[.]\d,(\d+)
Replace \1_\2,\3
```
```
C_pennsylvanicus,44
C_herculeanus,3
M_punctiventris,4
L_neoniger,55
```
```
Find (\w)\w+,(\w{4})\w+,\d+[.]\d,(\d+)
Replace \1_\2,\3

```
```
C_penn,44
C_herc,3
M_punc,4
L_neon,55
```





